# Generated by Django 4.2.11 on 2024-04-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_studentsubjectassignment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='passport',
        ),
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.ImageField(blank=True, upload_to='students/resumes/'),
        ),
    ]
